const FACEBOOK_APP_ID_LOCAL = "717242835144370";
const FACEBOOK_APP_SECRET_LOCAL = "cadb8177faf274df31b0ac086f27b9f2";
const TWITTER_CONSUMER_KEY_LOCAL = "LhkfMWrAOOxBsEeNhDVL6zYYk";
const TWITTER_CONSUMER_SECRET_LOCAL = "OjA7ucyFKKfEfeCMDAFVBy4u5dU2Vq3MJqqdmDwvHJwoflVTVL";
const OWNER_ID_LOCAL = "3232310030";
const TWITTER_ACCESS_TOKEN_KEY = "3232310030-SL7g4czDhzBf2HfoP15yJwBcF8bbobPmSSVu3FL";
const TWITTER_ACCESS_TOKEN_SECRET = "S5EUT3MdJWeQ0RDmZSqoVcWUlcpQe7UfhaYqIVIf4FyiQ";

module.exports = {
  FACEBOOK_APP_ID_LOCAL,
  FACEBOOK_APP_SECRET_LOCAL,
  TWITTER_CONSUMER_KEY_LOCAL,
  TWITTER_CONSUMER_SECRET_LOCAL,
  OWNER_ID_LOCAL,
  TWITTER_ACCESS_TOKEN_KEY,
  TWITTER_ACCESS_TOKEN_SECRET
};
